<?php
use eftec\chaosmachineone\ChaosMachineOne;

include 'common.php';

if($db->from('Countries')->count()>0) {
    echo "table countries skipped<br>";
} else {
    echo "inserting countries<br>";

    $chaos->getDb()->insert('Countries', ['IdCountry' => 1, 'name' => 'Afghanistan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 2, 'name' => 'Albania']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 3, 'name' => 'Algeria']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 4, 'name' => 'American Samoa']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 5, 'name' => 'Andorra']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 6, 'name' => 'Angola']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 7, 'name' => 'Anguilla']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 8, 'name' => 'Antigua And Barbuda']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 9, 'name' => 'Argentina']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 10, 'name' => 'Armenia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 11, 'name' => 'Aruba']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 12, 'name' => 'Australia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 13, 'name' => 'Austria']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 14, 'name' => 'Azerbaijan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 15, 'name' => 'Bahamas, The']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 16, 'name' => 'Bahrain']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 17, 'name' => 'Bangladesh']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 18, 'name' => 'Barbados']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 19, 'name' => 'Belarus']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 20, 'name' => 'Belgium']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 21, 'name' => 'Belize']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 22, 'name' => 'Benin']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 23, 'name' => 'Bermuda']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 24, 'name' => 'Bhutan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 25, 'name' => 'Bolivia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 26, 'name' => 'Bosnia And Herzegovina']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 27, 'name' => 'Botswana']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 28, 'name' => 'Brazil']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 29, 'name' => 'Brunei']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 30, 'name' => 'Bulgaria']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 31, 'name' => 'Burkina Faso']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 32, 'name' => 'Burundi']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 33, 'name' => 'Cabo Verde']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 34, 'name' => 'Cambodia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 35, 'name' => 'Cameroon']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 36, 'name' => 'Canada']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 37, 'name' => 'Cayman Islands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 38, 'name' => 'Central African Republic']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 39, 'name' => 'Chad']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 40, 'name' => 'Chile']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 41, 'name' => 'China']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 42, 'name' => 'Christmas Island']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 43, 'name' => 'Colombia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 44, 'name' => 'Comoros']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 45, 'name' => 'Congo (Brazzaville)']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 46, 'name' => 'Congo (Kinshasa)']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 47, 'name' => 'Cook Islands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 48, 'name' => 'Costa Rica']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 49, 'name' => 'Côte D’Ivoire']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 50, 'name' => 'Croatia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 51, 'name' => 'Cuba']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 52, 'name' => 'Curaçao']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 53, 'name' => 'Cyprus']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 54, 'name' => 'Czechia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 55, 'name' => 'Denmark']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 56, 'name' => 'Djibouti']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 57, 'name' => 'Dominica']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 58, 'name' => 'Dominican Republic']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 59, 'name' => 'Ecuador']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 60, 'name' => 'Egypt']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 61, 'name' => 'El Salvador']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 62, 'name' => 'Equatorial Guinea']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 63, 'name' => 'Eritrea']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 64, 'name' => 'Estonia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 65, 'name' => 'Ethiopia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 66, 'name' => 'Falkland Islands (Islas Malvinas)']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 67, 'name' => 'Faroe Islands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 68, 'name' => 'Fiji']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 69, 'name' => 'Finland']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 70, 'name' => 'France']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 71, 'name' => 'French Guiana']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 72, 'name' => 'French Polynesia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 73, 'name' => 'Gabon']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 74, 'name' => 'Gambia, The']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 75, 'name' => 'Gaza Strip']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 76, 'name' => 'Georgia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 77, 'name' => 'Germany']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 78, 'name' => 'Ghana']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 79, 'name' => 'Gibraltar']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 80, 'name' => 'Greece']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 81, 'name' => 'Greenland']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 82, 'name' => 'Grenada']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 83, 'name' => 'Guadeloupe']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 84, 'name' => 'Guam']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 85, 'name' => 'Guatemala']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 86, 'name' => 'Guinea']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 87, 'name' => 'Guinea-Bissau']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 88, 'name' => 'Guyana']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 89, 'name' => 'Haiti']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 90, 'name' => 'Honduras']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 91, 'name' => 'Hong Kong']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 92, 'name' => 'Hungary']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 93, 'name' => 'Iceland']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 94, 'name' => 'India']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 95, 'name' => 'Indonesia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 96, 'name' => 'Iran']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 97, 'name' => 'Iraq']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 98, 'name' => 'Ireland']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 99, 'name' => 'Isle Of Man']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 100, 'name' => 'Israel']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 101, 'name' => 'Italy']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 102, 'name' => 'Jamaica']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 103, 'name' => 'Japan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 104, 'name' => 'Jersey']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 105, 'name' => 'Jordan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 106, 'name' => 'Kazakhstan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 107, 'name' => 'Kenya']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 108, 'name' => 'Kiribati']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 109, 'name' => 'Korea, North']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 110, 'name' => 'Korea, South']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 111, 'name' => 'Kosovo']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 112, 'name' => 'Kuwait']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 113, 'name' => 'Kyrgyzstan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 114, 'name' => 'Laos']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 115, 'name' => 'Latvia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 116, 'name' => 'Lebanon']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 117, 'name' => 'Lesotho']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 118, 'name' => 'Liberia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 119, 'name' => 'Libya']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 120, 'name' => 'Liechtenstein']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 121, 'name' => 'Lithuania']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 122, 'name' => 'Luxembourg']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 123, 'name' => 'Macau']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 124, 'name' => 'Macedonia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 125, 'name' => 'Madagascar']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 126, 'name' => 'Malawi']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 127, 'name' => 'Malaysia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 128, 'name' => 'Maldives']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 129, 'name' => 'Mali']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 130, 'name' => 'Malta']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 131, 'name' => 'Marshall Islands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 132, 'name' => 'Martinique']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 133, 'name' => 'Mauritania']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 134, 'name' => 'Mauritius']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 135, 'name' => 'Mayotte']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 136, 'name' => 'Mexico']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 137, 'name' => 'Micronesia, Federated States Of']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 138, 'name' => 'Moldova']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 139, 'name' => 'Monaco']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 140, 'name' => 'Mongolia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 141, 'name' => 'Montenegro']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 142, 'name' => 'Morocco']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 143, 'name' => 'Mozambique']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 144, 'name' => 'Myanmar']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 145, 'name' => 'Namibia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 146, 'name' => 'Nepal']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 147, 'name' => 'Netherlands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 148, 'name' => 'New Caledonia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 149, 'name' => 'New Zealand']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 150, 'name' => 'Nicaragua']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 151, 'name' => 'Niger']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 152, 'name' => 'Nigeria']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 153, 'name' => 'Niue']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 154, 'name' => 'Norfolk Island']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 155, 'name' => 'Northern Mariana Islands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 156, 'name' => 'Norway']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 157, 'name' => 'Oman']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 158, 'name' => 'Pakistan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 159, 'name' => 'Palau']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 160, 'name' => 'Panama']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 161, 'name' => 'Papua New Guinea']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 162, 'name' => 'Paraguay']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 163, 'name' => 'Peru']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 164, 'name' => 'Philippines']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 165, 'name' => 'Pitcairn Islands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 166, 'name' => 'Poland']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 167, 'name' => 'Portugal']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 168, 'name' => 'Puerto Rico']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 169, 'name' => 'Qatar']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 170, 'name' => 'Reunion']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 171, 'name' => 'Romania']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 172, 'name' => 'Russia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 173, 'name' => 'Rwanda']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 174, 'name' => 'Saint Barthelemy']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 175, 'name' => 'Saint Helena, Ascension, And Tristan Da Cunha']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 176, 'name' => 'Saint Kitts And Nevis']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 177, 'name' => 'Saint Lucia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 178, 'name' => 'Saint Martin']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 179, 'name' => 'Saint Pierre And Miquelon']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 180, 'name' => 'Saint Vincent And The Grenadines']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 181, 'name' => 'Samoa']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 182, 'name' => 'San Marino']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 183, 'name' => 'Sao Tome And Principe']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 184, 'name' => 'Saudi Arabia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 185, 'name' => 'Senegal']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 186, 'name' => 'Serbia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 187, 'name' => 'Seychelles']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 188, 'name' => 'Sierra Leone']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 189, 'name' => 'Singapore']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 190, 'name' => 'Sint Maarten']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 191, 'name' => 'Slovakia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 192, 'name' => 'Slovenia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 193, 'name' => 'Solomon Islands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 194, 'name' => 'Somalia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 195, 'name' => 'South Africa']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 196, 'name' => 'South Georgia And South Sandwich Islands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 197, 'name' => 'South Sudan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 198, 'name' => 'Spain']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 199, 'name' => 'Sri Lanka']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 200, 'name' => 'Sudan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 201, 'name' => 'Suriname']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 202, 'name' => 'Svalbard']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 203, 'name' => 'Swaziland']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 204, 'name' => 'Sweden']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 205, 'name' => 'Switzerland']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 206, 'name' => 'Syria']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 207, 'name' => 'Taiwan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 208, 'name' => 'Tajikistan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 209, 'name' => 'Tanzania']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 210, 'name' => 'Thailand']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 211, 'name' => 'Timor-Leste']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 212, 'name' => 'Togo']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 213, 'name' => 'Tonga']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 214, 'name' => 'Trinidad And Tobago']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 215, 'name' => 'Tunisia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 216, 'name' => 'Turkey']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 217, 'name' => 'Turkmenistan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 218, 'name' => 'Turks And Caicos Islands']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 219, 'name' => 'Tuvalu']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 220, 'name' => 'Uganda']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 221, 'name' => 'Ukraine']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 222, 'name' => 'United Arab Emirates']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 223, 'name' => 'United Kingdom']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 224, 'name' => 'United States']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 225, 'name' => 'Uruguay']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 226, 'name' => 'Uzbekistan']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 227, 'name' => 'Vanuatu']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 228, 'name' => 'Vatican City']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 229, 'name' => 'Venezuela']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 230, 'name' => 'Vietnam']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 231, 'name' => 'Virgin Islands, British']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 232, 'name' => 'Wallis And Futuna']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 233, 'name' => 'West Bank']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 234, 'name' => 'Western Sahara']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 235, 'name' => 'Yemen']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 236, 'name' => 'Zambia']);
    $chaos->getDb()->insert('Countries', ['IdCountry' => 237, 'name' => 'Zimbabwe']);

    echo "inserting countries OK<br>";
}