<?php

class SakilaLib {
    
    public $subjectTitle=['Teacher','Car','Lumberjack','Monkey','Forensic Psychologist','Sumo Wrestler','Butler'
                     ,'Mad Scientist','Feminist','Pastry Chef','Boy','Pioneer','Astronaut','Boat','Secret Agent'
                     ,'Man','Student','Database Administrator','Girl','Robot','Woman','Dog','Waitress','Explorer'
                     ,'Composer','Dentist','Technical Writer','Husband','Moose','A Shark','Crocodile','Madman'
                     ,'Cat','Squirrel','Hunter','Frisbee','Mad Cow','Womanizer'];
    
    public $locationTitle=['The Canadian Rockies','Ancient China','A Baloon Factory','A Shark Tank','The Gulf of Mexico'
                      ,'A Jet Boat','Ancient India','A MySQL Convention','Australia','Soviet Georgia'
                      ,'New Orleans','An Abandoned Fun House','A Baloon','California','The Sahara Desert'
                      ,'Berlin','An Abandoned Amusement Park','A U-Boat','An Abandoned Mine Shaft','Nigeria'
                      ,'The First Manned Space Station','A Monastery','Ancient Japan'
                      ,'A Manhattan Penthouse','The Outback'];
    PUBLIC $mustTitle=['Battle','Find','Sink','Chase','Pursue','Escape','Discover','Confront','Outgun','Reach'
                       ,'Fight','Vanquish','Meet','Conquer','Face','Overcome','Outrace','Succumb','Defeat','Challenge'
                       ,'Kill','Build','Redeem'];
    
    public $verbTitle=['Epic','Astounding','Fanciful','Fast-Paced','Intrepid','Touching','Thoughtful','Action-Packed'
                  ,'Boring','Emotional','Brilliant','Insightful','Lacklusture','Amazing','Fateful','Awe-Inspiring'
                  ,'Beautiful','Stunning','Thrilling','Unbelieveable','Taut'];
    
    public $categoryTitle=['Drama','Epistle','Reflection','Documentary','Panorama','Saga','Tale','Character Study'
                      ,'Display','Yarn','Story'];
    
    public $filmDescArr=['A {{verbTitle}} {{categoryTitle}} of a {{subjectTitle}} and a {{subjectTitle}} who must {{mustTitle}} in {{locationTitle}}'];

    Public $Title=['Academy','Ace','Adaptation','Affair','African','Agent','Airplane','Airport','Alabama','Aladdin'
                   ,'Alamo','Alaska','Ali','Alice','Alien','Alley','Alone','Alter','Amadeus','Amelie','American'
                   ,'Amistad','Anaconda','Analyze','Angels','Annie','Anonymous','Anthem','Antitrust','Anything'
                   ,'Apache','Apocalypse','Apollo','Arabia','Arachnophobia','Argonauts','Arizona','Ark','Armageddon'
                   ,'Army','Arsenic','Artist','Atlantis','Attacks','Attraction','Autumn','Baby','Backlash','Badman'
                   ,'Baked','Balloon','Ballroom','Bang','Banger','Barbarella','Barefoot','Basic','Beach','Bear'
                   ,'Beast','Beauty','Bed','Bedazzled','Beethoven','Behavior','Beneath','Berets','Betrayed','Beverly'
                   ,'Bikini','Bilko','Bill','Bingo','Birch','Bird','Birdcage','Birds','Blackout','Blade','Blanket'
                   ,'Blindness','Blood','Blues','Boiled','Bonnie','Boogie','Boondock','Born','Borrowers','Boulevard'
                   ,'Bound','Bowfinger','Brannigan','Braveheart','Breakfast','Breaking','Bride','Bright','Bringing'
                   ,'Brooklyn','Brotherhood','Bubble','Bucket','Bugsy','Bull','Bulworth','Bunch','Butch','Butterfly'
                   ,'Cabin','Caddyshack','Calendar','California','Camelot','Campus','Candidate','Candles','Canyon'
                   ,'Caper','Caribbean','Carol','Carrie','Casablanca','Casper','Cassidy','Casualties','Cat'
                   ,'Catch','Cause','Celebrity','Center','Chainsaw','Chamber','Champion','Chance','Chaplin'
                   ,'Charade','Chariots','Chasing','Cheaper','Chicago','Chicken','Chill','Chinatown','Chisum'
                   ,'Chitty','Chocolat','Chocolate','Christmas','Cider','Cincinatti','Circus','Citizen','Clash'
                   ,'Cleopatra','Clerks','Clockwork','Clones','Closer','Club','Clue','Clueless','Clyde','Coast'
                   ,'Coldblooded','Color','Coma','Comancheros','Comforts','Command','Commandments','Coneheads'
                   ,'Confessions','Confidential','Confused','Congeniality','Connecticut','Connection','Conquerer'
                   ,'Conspiracy','Contact','Control','Conversation','Core','Cowboy','Craft','Cranes','Crazy'
                   ,'Creatures','Creepers','Crooked','Crossing','Crossroads','Crow','Crowds','Cruelty','Crusade'
                   ,'Crystal','Cupboard','Curtain','Cyclone','Daddy','Daisy','Dalmations','Dances','Dancing'
                   ,'Dangerous','Dares','Darkness','Darko','Darling','Darn','Date','Daughter','Dawn','Day'
                   ,'Dazed','Deceiver','Deep','Deer','Deliverance','Desert','Desire','Desperate','Destination'
                   ,'Destiny','Details','Detective','Devil','Diary','Dinosaur','Dirty','Disciple','Disturbing'
                   ,'Divide','Divine','Divorce','Doctor','Dogma','Dolls','Donnie','Doom','Doors','Dorado'
                   ,'Double','Doubtfire','Downhill','Dozen','Dracula','Dragon','Dragonfly','Dream','Drifter'
                   ,'Driver','Driving','Drop','Drumline','Drums','Duck','Dude','Duffel','Dumbo','Durham','Dwarfs'
                   ,'Dying','Dynamite','Eagles','Early','Earring','Earth','Easy','Edge','Effect','Egg','Egypt'
                   ,'Element','Elephant','Elf','Elizabeth','Empire','Encino','Encounters','Ending','Enemy','English'
                   ,'Enough','Entrapment','Escape','Eve','Everyone','Evolution','Excitement','Exorcist','Expecations'
                   ,'Expendable','Express','Extraordinary','Eyes','Factory','Falcon','Family','Fantasia'
                   ,'Fantasy','Fargo','Fatal','Feathers','Fellowship','Ferris','Feud','Fever','Fiction','Fiddler'
                   ,'Fidelity','Fight','Finding','Fire','Fireball','Firehouse','Fish','Flamingos','Flash'
                   ,'Flatliners','Flight','Flintstones','Floats','Flying','Fool','Forever','Forrest','Forrester'
                   ,'Forward','Frankenstein','Freaky','Freddy','Freedom','French','Frida','Frisco','Frogmen'
                   ,'Frontier','Frost','Fugitive','Full','Fury','Gables','Galaxy','Games','Gandhi','Gangs','Garden'
                   ,'Gaslight','Gathering','Gentlemen','Ghost','Ghostbusters','Giant','Gilbert','Gilmore'
                   ,'Gladiator','Glass','Gleaming','Glory','Go','Godfather','Gold','Goldfinger','Goldmine'
                   ,'Gone','Goodfellas','Gorgeous','Gosford','Graceland','Graduate','Graffiti','Grail','Grapes'
                   ,'Grease','Greatest','Greedy','Greek','Grinch','Grit','Groove','Grosse','Groundhog','Gump'
                   ,'Gun','Gunfight','Gunfighter','Guys','Half','Hall','Halloween','Hamlet','Handicap','Hanging'
                   ,'Hanky','Hanover','Happiness','Hardly','Harold','Harper','Harry','Hate','Haunted','Haunting'
                   ,'Hawk','Head','Heartbreakers','Heaven','Heavenly','Heavyweights','Hedwig','Hellfighters'
                   ,'High','Highball','Hills','Hobbit','Hocus','Holes','Holiday','Hollow','Hollywood','Holocaust'
                   ,'Holy','Home','Homeward','Homicide','Honey','Hook','Hoosiers','Hope','Horn','Horror','Hotel'
                   ,'Hours','House','Human','Hunchback','Hunger','Hunter','Hunting','Hurricane','Hustler','Hyde'
                   ,'Hysterical','Ice','Idaho','Identity','Idols','Igby','Illusion','Image','Impact','Impossible'
                   ,'Inch','Independence','Indian','Informer','Innocent','Insects','Insider','Instinct','Intentions'
                   ,'Interview','Intolerable','Intrigue','Invasion','Iron','Ishtar','Island','Italian','Jacket'
                   ,'Jade','Japanese','Jason','Jawbreaker','Jaws','Jedi','Jeepers','Jekyll','Jeopardy','Jericho'
                   ,'Jerk','Jersey','Jet','Jingle','Joon','Juggler','Jumanji','Jumping','Jungle','Kane','Karate'
                   ,'Kentuckian','Kick','Kill','Killer','King','Kiss','Kissing','Knock','Kramer','Kwai','Labyrinth'
                   ,'Lady','Ladybugs','Lambs','Language','Lawless','Lawrence','League','Leathernecks','Lebowski'
                   ,'Legally','Legend','Lesson','Liaisons','Liberty','License','Lies','Life','Lights','Lion'
                   ,'Loathing','Lock','Lola','Lolita','Lonely','Lord','Lose','Loser','Lost','Louisiana','Love'
                   ,'Lovely','Lover','Loverboy','Luck','Lucky','Luke','Lust','Madigan','Madison','Madness'
                   ,'Madre','Magic','Magnificent','Magnolia','Maguire','Maiden','Majestic','Maker','Malkovich'
                   ,'Mallrats','Maltese','Manchurian','Mannequin','Married','Mars','Mask','Masked','Massacre'
                   ,'Massage','Matrix','Maude','Meet','Memento','Menagerie','Mermaid','Metal','Metropolis'
                   ,'Microcosmos','Midnight','Midsummer','Mighty','Mile','Million','Minds','Mine','Minority'
                   ,'Miracle','Mission','Mixed','Mob','Mockingbird','Mod','Model','Modern','Money','Monsoon'
                   ,'Monster','Monterey','Montezuma','Moon','Moonshine','Moonwalker','Mosquito','Mother'
                   ,'Motions','Moulin','Mourning','Movie','Mulan','Mulholland','Mummy','Muppet','Murder','Muscle'
                   ,'Music','Musketeers','Mussolini','Mystic','Name','Nash','National','Natural','Necklace'
                   ,'Neighbors','Nemo','Network','Newsies','Newton','Nightmare','None','Noon','North','Northwest'
                   ,'Notorious','Notting','Novocaine','Nuts','October','Odds','Oklahoma','Oleander','Open'
                   ,'Operation','Opposite','Opus','Orange','Order','Orient','Oscar','Others','Outbreak','Outfield'
                   ,'Outlaw','Oz','Pacific','Packer','Pajama','Panic','Panky','Panther','Papi','Paradise','Paris'
                   ,'Park','Party','Past','Paths','Patient','Patriot','Patton','Paycheck','Peach','Peak','Pearl'
                   ,'Pelican','Perdition','Perfect','Personal','Pet','Phantom','Philadelphia','Pianist','Pickup'
                   ,'Pilot','Pinocchio','Pirates','Pittsburgh','Pity','Pizza','Platoon','Pluto','Pocus','Polish'
                   ,'Pollock','Pond','Poseidon','Potluck','Potter','Prejudice','President','Pride','Primary'
                   ,'Princess','Private','Prix','Psycho','Pulp','Punk','Pure','Purple','Queen','Quest','Quills'
                   ,'Racer','Rage','Raging','Raiders','Rainbow','Random','Range','Reap','Rear','Rebel','Records'
                   ,'Redemption','Reds','Reef','Reign','Remember','Requiem','Reservoir','Resurrection','Reunion'
                   ,'Rider','Ridgemont','Right','Rings','River','Road','Robbers','Robbery','Rock','Rocketeer'
                   ,'Rocky','Rollercoaster','Roman','Roof','Room','Roots','Roses','Rouge','Roxanne','Rugrats'
                   ,'Rules','Run','Runaway','Runner','Rush','Rushmore','Sabrina','Saddle','Sagebrush','Saints'
                   ,'Salute','Samurai','Santa','Sassy','Satisfaction','Saturday','Saturn','Savannah','Scalawag'
                   ,'Scarface','School','Scissorhands','Scorpion','Sea','Seabiscuit','Searchers','Seattle','Secret'
                   ,'Secretary','Secrets','Sense','Sensibility','Seven','Shakespeare','Shane','Shanghai','Shawshank'
                   ,'Shepherd','Shining','Ship','Shock','Shootist','Show','Shrek','Shrunk','Side','Siege','Sierra'
                   ,'Silence','Silverado','Simon','Sinners','Sister','Sky','Slacker','Sleeping','Sleepless','Sleepy'
                   ,'Sleuth','Sling','Slipper','Slums','Smile','Smoking','Smoochy','Snatch','Snatchers','Snowman'
                   ,'Soldiers','Something','Song','Sons','Sorority','Soup','South','Spartacus','Speakeasy','Speed'
                   ,'Spice','Spiking','Spinal','Spirit','Spirited','Splash','Splendor','Spoilers','Spy','Squad'
                   ,'Stage','Stagecoach','Stallion','Stampede','Star','State','Steel','Steers','Stepmom','Sting'
                   ,'Stock','Stone','Storm','Story','Straight','Strangelove','Stranger','Strangers','Streak'
                   ,'Streetcar','Strictly','Submarine','Sugar','Suicides','Suit','Summer','Sun','Sundance'
                   ,'Sunrise','Sunset','Super','Superfly','Suspects','Swarm','Sweden','Sweet','Sweethearts'
                   ,'Tadpole','Talented','Tarzan','Taxi','Teen','Telegraph','Telemark','Temple','Tenenbaums'
                   ,'Tequila','Terminator','Texas','Theory','Thief','Thin','Ties','Tights','Timberland','Titanic'
                   ,'Titans','Tomatoes','Tomorrow','Tootsie','Torque','Tourist','Towers','Town','Tracy','Trading'
                   ,'Traffic','Train','Trainspotting','Tramp','Translation','Trap','Treasure','Treatment','Trip'
                   ,'Trojan','Troopers','Trouble','Truman','Turn','Tuxedo','Twisted','Tycoon','Unbreakable','Uncut'
                   ,'Undefeated','Unfaithful','Unforgiven','United','Untouchables','Uprising','Uptown','Usual'
                   ,'Vacation','Valentine','Valley','Vampire','Vanilla','Vanished','Vanishing','Varsity','Velvet'
                   ,'Vertigo','Victory','Videotape','Vietnam','Villain','Virgin','Virginian','Virtual','Vision'
                   ,'Voice','Volcano','Volume','Voyage','Wagon','Wait','Wake','Walls','Wanda','War','Wardrobe'
                   ,'Warlock','Wars','Wash','Wasteland','Watch','Waterfront','Watership','Wedding','Weekend','Werewolf'
                   ,'West','Westward','Whale','Whisperer','Wife','Wild','Willow','Wind','Window','Wisdom','Witches'
                   ,'Wizard','Wolves','Women','Won','Wonderful','Wonderland','Wonka','Words','Worker','Working','World'
                   ,'Worst','Wrath','Wrong','Wyoming','Yentl','Young','Youth','Zhivago','Zoolander','Zorro'];
    
    public $rating=['PG','G','NC-17','PG-13','R','NR'];
    
    public $features=['Deleted Scenes','Behind the Scenes','Trailers','Commentaries','Alternate ending'
                      ,'Audio commentary','B-roll','Blooper','Footage','Making-of','Music video','Outtake'
                      ,'Film still','Storyboard'];
    public $featuresArr=['','{{features}}','{{features}},{{features}}','{{features}},{{features}},{{features}}'];

    public $category=['Action','Animation','Children','Classics','Comedy','Documentary','Drama','Family','Fantasy',
                      'Foreign','Games','Horror','Music','Mystery','New','Romance','Sci-Fi','Sports','Thriller'
                      ,'Travel','Western'];
    
    public $language=['English', 'Italian', 'Japanese', 'Mandarin', 'French', 'German','Spanish'];
    
    public $actorName=['Penelope','Nick','Ed','Jennifer','Johnny','Bette','Grace','Matthew','Joe','Christian','Zero'
                       ,'Karl','Uma','Vivien','Cuba','Fred','Helen','Dan','Bob','Lucille','Kirsten','Elvis','Sandra'
                       ,'Cameron','Kevin','Rip','Julia','Woody','Alec','Sissy','Tim','Milla','Audrey','Judy','Burt'
                       ,'Val','Tom','Goldie','Jodie','Kirk','Reese','Parker','Frances','Anne','Natalie','Gary','Carmen'
                       ,'Mena','Fay','Jude','Dustin','Henry','Jayne','Ray','Angela','Mary','Jessica','Kenneth'
                       ,'Michelle','Adam','Sean','Angelina','Cary','Groucho','Mae','Ralph','Scarlett','Ben','James'
                       ,'Minnie','Greg','Spencer','Charlize','Christopher','Ellen','Daryl','Gene','Meg','Chris'
                       ,'Jim','Susan','Walter','Sidney','Gina','Warren','Sylvester','Russell','Morgan','Harrison'
                       ,'Renee','Liza','Salma','Julianne','Albert','Cate','Greta','Jane','Richard','Rita','Ewan'
                       ,'Whoopi','Jada','River','Kim','Emily','Geoffrey','Meryl','Ian','Laura','Harvey','Oprah'
                       ,'Humphrey','Al','Laurence','Will','Olympia','Alan','Michael','William','Jon','Lisa','Jeff'
                       ,'Debbie','Rock','Gregory','John','Bela','Thora'];
    
    public $actorLastName=['Guiness','Wahlberg','Chase','Davis','Lollobrigida','Nicholson','Mostel','Johansson'
                           ,'Swank','Gable','Cage','Berry','Wood','Bergen','Olivier','Costner','Voight','Torn'
                           ,'Fawcett','Tracy','Paltrow','Marx','Kilmer','Streep','Bloom','Crawford','Mcqueen'
                           ,'Hoffman','Wayne','Peck','Sobieski','Hackman','Dean','Dukakis','Bolger','Mckellen'
                           ,'Brody','Degeneres','Miranda','Jovovich','Stallone','Goldberg','Barrymore','Day-Lewis'
                           ,'Cronyn','Hopkins','Phoenix','Hunt','Temple','Pinkett','Harris','Cruise','Akroyd','Tautou'
                           ,'Neeson','Wray','Hudson','Tandy','Bailey','Winslet','Mcconaughey','Grant','Williams','Penn'
                           ,'Keitel','Posey','Astaire','Sinatra','Cruz','Damon','Jolie','Willis','Pitt','Zellweger'
                           ,'Chaplin','Pesci','Dench','Presley','Hawke','Bridges','Depp','Leigh','Crowe','Dunst'
                           ,'Nolte','Dern','Bacall','Mcdormand','Bale','Allen','Jackman','Monroe','Bergman','Bening'
                           ,'Tomei','Garland','Hopper','Reynolds','Mansfield','Dee','Gooding','Hurt','Ryder'
                           ,'Witherspoon','Heston','Gibson','Malden','Basinger','Hope','West','Bullock','Wilson'
                           ,'Pfeiffer','Dreyfuss','Silverstone','Carrey','Close','Ball','Birch','Suvari','Walken'];
}